### ISSUE TITLE
TLDR: Don't Use Saily If You Don't Want to Take Responsibility On Your Own

### ISSUE THREAD

**Issue by CallMeEchoCodes** [SailyTeam/Saily#104]
I have a feeling this will get deleted but here we go

@MasterMike88 On twitter made an amazing thread on all the issues with Saily. Please read it. I'm not going to waste time describing all the issues in detail when i already have this thread to do it for me.
https://twitter.com/MasterMike88/status/1602195668344389633

For now i have to recommend that you don't use Saily but i want to see it improve, that's why I'm making this issue!
Saily has a great UI and i would love to use it but i can't overlook the very real possibility of it causing bootloops. I'm not an iOS expert, far from it. But i know a little bit about programming and project management so i have some advice:

#### **Don't ignore issues just because they are hard to fix.**
 Yes some of these issues are hard to fix but you have a responsibility as a maintainer to fix them and **tell people about the issues**.  I would have just told people to stop using Saily but its integrated into a big jailbreak now (XinaA15) making it a lot harder.

I hope you can address the issues outlined in the twitter thread by @MasterMike88.

Well that's all thanks for reading my huge monologue 

~~### ***TLDR: Saily has major issues and has the potential to break devices. Stop using it until it gets fixed***~~
Owner Speaking Here:
Saily on root jailbreak uses apt, and it will ack like a safe guard.
Saily on rootless jailbreak uses dpkg, and eveything changed is applied to rootless environment, you won't have a chance to mess it up.
Lastly, you are on your own checking everything. Using Sileo or apt or another stuff with a malware crafted package will all damage your system. Saily has a complete check over dependency, but that doesn't mean it will work 100%, apt/Sileo is too.

**Comment by Lakr233** [comment]
> I have a feeling this will get deleted but here we go

I never delete a post, or remove the text you wrote. Feel free to just walk away or repost my statement. Put this in wayback machine. I will welcome any one to post their opinion here, and I won't block anyone.

**Comment by Lakr233** [comment]
Something interesting: https://twitter.com/mastermike88/status/1602235932547096577

```
depends: firmware (>=8.0), mobilesubstrate, preferenceloader, com.opa334.libsandy, com.opa334.libundirect (>=1.1.3) | firmware (<<14.0), ws.hbang.common | firmware (>=11.0), com.creaturesurvive.libcscolorpicker | ws.hbang.alderis (>= 1.1)
package: com.opa334.safariplus
sha1: 868dc44f68c646ad3c9fd529aa7ae3882fb06523
```

The dependency means:

```
firmware (>=8.0),
mobilesubstrate,
preferenceloader,
com.opa334.libsandy,
com.opa334.libundirect (>=1.1.3) | firmware (<<14.0),
ws.hbang.common | firmware (>=11.0),
com.creaturesurvive.libcscolorpicker | ws.hbang.alderis (>= 1.1)
```

For a clean Xina 15 installation, the dependencies are:
```
firmware (>=8.0),
mobilesubstrate,
preferenceloader,
```

For Extra Dependencies, the dependencies are:
```
com.opa334.libsandy,
com.opa334.libundirect (>=1.1.3) | firmware (<<14.0),
ws.hbang.common | firmware (>=11.0),
com.creaturesurvive.libcscolorpicker | ws.hbang.alderis (>= 1.1)
```

On iOS 15, Saily resolved the dependency as:
```
com.opa334.libsandy,
com.opa334.libundirect (>=1.1.3) 
com.creaturesurvive.libcscolorpicker
```

This is a working install. So I don't know what he is talking about. I might need a talk with opa334.
![IMG_E39E0825B4D2-1](https://user-images.githubusercontent.com/25259084/207509370-385202c4-fb0a-4b7e-bab6-d7af3418d974.jpeg)

**Comment by Lakr233** [comment]
https://twitter.com/MasterMike88/status/1602195663990685697

The post says:
```
Saily letting a tweak install that isn't compatible and then not allowing it to uninstall because it wants to try to uninstall Essentials

(Common theme for later: Saily will basically let anything go through and will ignore every issue/error that should otherwise exist)
```

My reply:

Yes, and it is you to press the button, and it is a double press/check, no mis-touch will happen. And if you uninstall the essential, a triple check is applied with alert.

> Saily will basically let anything go through and will ignore every issue/error that should otherwise exist

That is following your order. You the one approved this. Did I hide it? NO.

**Comment by Lakr233** [comment]
https://twitter.com/MasterMike88/status/1602195668344389633

The post said:
```
Saily not giving an error about a needed dependency for a package and just letting it go through because why not.
```

My Reply:
Here are the libSparkAppList manifest:
```
architecture: iphoneos-arm
author: Spark
depiction: https://www.sparkdev.me/package/com.spark.libsparkapplist
description: AppList alternative
filename: download/com.spark.libsparkapplist/1.0.10.deb
icon: https://sparkdev.me/package-logo/com.spark.libsparkapplist
installed-size: 404
maintainer: Spark
md5sum: 7ea393c06401822def242bc36e4b93b3
name: libSparkAppList
package: com.spark.libsparkapplist
section: System
sha1: 1fe0728cfabddba85543fe2d4a2390f18ccedc6b
sha256: 4f804a14a026ff8e64c19653ea605c637dc857c996d297c982e5b2f4a68a609b
sileodepiction: https://www.sparkdev.me/sileo/com.spark.libsparkapplist
size: 27440
tag: purpose::extension
version: 1.0.10
```

I didn't see any error/problem install with it. If there is, there is conflict on your system environment. Saily checks conflicts, and if exists, it will be added to removal queue.

**Comment by Lakr233** [comment]
https://twitter.com/MasterMike88/status/1602195672211537920

The Post Said:
```
Saily allowing a package to install that it shouldn't have tried to install in the first place

(Sidenote: Saily also goes and nukes dpkg lockfiles - something you should **never** do - because why not I guess)
```

I don't know what's the problem with Saily, you are trying to install it, package manifest checked ok, dependency checked ok, then why `it shouldn't have tried to install in the first place`? Did the package said `firmware (< 15.0)`? NO.

> Saily also goes and nukes dpkg lockfiles

Sure, you press the button telling me to go on, I remove the lockfile so you can install things.

If a dpkg is broken, remove the lockfile are very common. If you want to fix it yourself, you check if dpkg is running and if not, remove the lock is what you will do.

On iOS device, there won't be a change to have it unless you mean to, sure you can with some hack or ssh stuff, then you are all on your own.

**Comment by kirb** [comment]
> If a dpkg is broken, remove the lockfile are very common. If you want to fix it yourself, you check if dpkg is running and if not, remove the lock is what you will do.

Debian specifically advises to never do that:

> Removing the dpkg lock files is **never** a correct solution, as dpkg uses region locking (on existing files) which are bound to a process, so once the process finishes or is killed the lock is automatically released (and dpkg itself never removes the lock file). The presence of the file does not mean that the lock is currently being held, and removing them can most probably cause dpkg database or filesystem corruption. If there is ever a need to override the locks, then it is **always** preferable to kill an active running dpkg over ever removing the lock files, as dpkg is supposed to be resilient against abrupt system or process crashes or termination, and any issues stemming from those would be considered serious problems in need of fixing.

https://wiki.debian.org/Teams/Dpkg/FAQ#Q:_What_can_be_done_when_the_dpkg_lock_is_held.3F

Messing with the lock is concerning, because you don’t know why it’s held, or whether you’ll be creating a race condition by overriding it. It might work 99% of the time, but I’m personally not prepared to play Russian roulette with users’ dpkg status files. We’re very lucky that deleting all jailbreak files and starting over is so easy these days, otherwise there would be zero tolerance to play with fire like this. I also wouldn’t guarantee that this never happens simply because you’ve never heard of it happening - if all package managers are showing the same weird error about status file failing to parse, the user probably doesn't know who to contact about it. So my best advice is just don’t do it.

**Comment by Lakr233** [comment]
Debian is not iOS, and iOS are not designed to have multiple user running the same thing.

So as you say: `It might work 99% of the time`, and the last 1% is caused either
- A: dpkg crashed, left the lock unremoved
- B: user are meant to run multiple dpkg themselves

iOS will make sure there is only one Saily running and if so, dpkg lock can be safely removed. If user is meant to use two package manager in the same time, nothing will get promised.

Designing a package manager is not about showing user how "geek" we are, and letting user fix some tiny stuff that won't be a problem most of time is not worth to. Again, there is no baby safe mechanism in Saily, and I won't do that.

**Comment by kirb** [comment]
I think you mistook what I meant by 99% (sorry, I realise there’s a language barrier) - I meant that it’s possible 99% of the time it’s safe to do, but the remaining 1% is because apt/dpkg **is** actually still running. It’s perfectly possible that a user tries to run multiple dpkg operations at once - users can be unpredictable! They don’t necessarily understand like we do that trying to run multiple operations on the same database simultaneously is a bad idea. Software engineering is all about handling edge cases as carefully as you possibly can, this is no exception to that rule.

I don’t want package managers to be difficult to use. To be clear, the reason I took over Zebra is because I want to make them as user-friendly as possible, yet still just as rock solid and safe to use, if not even safer than before. “Status file locked” should never *need* to be seen by a user, **but** you still need to look out for the integrity of the user’s device.

It would be worth testing the theory that the lockfile works on Darwin as documented by Debian. True, it might not actually clean up on termination, but it sounds like that hasn’t actually been confirmed. I’ll look into it soon because I want to make sure Zebra does the right thing here. At the moment, Zebra doesn’t do anything with the dpkg lockfiles, yet I don’t think we see many lockfile issues raised.

**Comment by Lakr233** [comment]
Thanks for your kind reply, please get me updated if you can confirm the file lock are removed on termination/working or anything else you have found.

I‘m considering an alert before removing the locks.
